### ISSUE TITLE
Open local web app

### ISSUE THREAD

**Issue by meduar** [rtctunnel/rtctunnel#119]
I understand the usage of webrtc here that would eliminate the traffic on the server(just for signalling) and then the traffic is  from peer to peer, excellent idea.

I am trying to understand if this could work for the following:

- I have a local web app that is on localhost:8080 and I need to access this app remotely from a phone(ios or android), could I access this app remotely with rtctunnel? 

If the answer is yes, how the content of the server page let's say index.html,js,css,images any content is shown on the client? would I have to print the content returned within my HTML app like let's say "hide.me that is a web proxy"? or could I put it in an iframe?

Thank you,

**Comment by calebdoxsey** [comment]
No it would not work. You would have to run rtctunnel on the phone.
