### ISSUE TITLE
pion is missing?

### ISSUE THREAD

**Issue by Zibri** [rtctunnel/rtctunnel#19]
$ go get github.com/rtctunnel/rtctunnel/cmd/rtctunnel
../../../go/src/github.com/pion/webrtc/interceptor.go:11:2: cannot find package "github.com/pion/rtp" in any of:
        /opt/hostedtoolcache/go/1.15.13/x64/src/github.com/pion/rtp (from $GOROOT) [.....]

**Comment by Zibri** [comment]
Nevermind.
Solution:
$ GO111MODULE=on
$ go get github.com/rtctunnel/rtctunnel/cmd/rtctunnel

add it to readme.md

**Comment by calebdoxsey** [comment]
Thanks. I updated the readme.

**Comment by Zibri** [comment]
it does not error out but it does not work either :/  but I am new to "go" so I really don't know.
