### ISSUE TITLE
default signaling server is now down

### ISSUE THREAD

**Issue by limbo127** [rtctunnel/rtctunnel#22]
hello, 
https://appr.tc does is now shutowing.
Can you provide an example with a new signaling server or set option for define own apprtc server
regards, 
Nicolas

**Comment by calebdoxsey** [comment]
Hi @limbo127 ,

I changed the default to a custom heroku app a while back: https://github.com/rtctunnel/rtctunnel/blob/bdd6927f211b57159de3ea3f94c24d06d69d5d8a/signal/signal.go#L16. Does that work?

Long term I'd like to switch to MQTT - there are a couple public servers out there that could be used.

**Comment by limbo127** [comment]
Hello, 
not for me 
[nicolasprochazka@localhost tmp]$  /home/nicolasprochazka/go/bin/rtctunnel run --log-level debug
{"level":"info","config-file":"/home/nicolasprochazka/.config/rtctunnel/rtctunnel.yaml","public-key":"TRSqcgGdNCD4Ew3Ueiz8BHm2E65rpTVnn55ogC4xUck","routes":[{"LocalPort":22,"LocalPeer":[6,196,189,219,205,87,110,98,5,44,46,40,7,53,81,238,28,106,117,152,188,118,129,134,87,168,77,148,20,133,125,77],"RemotePeer":[165,191,40,251,255,78,123,172,57,52,17,25,47,213,39,148,107,154,73,11,251,84,122,109,33,70,180,215,37,60,53,126],"RemotePort":22}],"signal-channel":"","time":"2022-02-10T22:16:58+01:00","message":"using config"}
{"level":"info","peer":"CA1LKWSDV8s3Dm4vos2dsNAFQiHX42umubBiEjbXdR73","time":"2022-02-10T22:16:58+01:00","message":"creating webrtc peer connection"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6ff818]

goroutine 1 [running]:
github.com/rtctunnel/rtctunnel/channels/apprtc.(*apprtcChannel).getConnection(0xc0002ae4e0, {0xc0002ae4e0, 0x58}, {0x930378, 0x4})
	/home/nicolasprochazka/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/channels/apprtc/apprtc.go:77 +0x158
github.com/rtctunnel/rtctunnel/channels/apprtc.(*apprtcChannel).Recv(0xc00018f698, {0xc0002ae4e0, 0x0})
	/home/nicolasprochazka/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/channels/apprtc/apprtc.go:29 +0x5f
github.com/rtctunnel/rtctunnel/signal.Recv({{0x6, 0xc4, 0xbd, 0xdb, 0xcd, 0x57, 0x6e, 0x62, 0x5, 0x2c, ...}, ...}, ...)
	/home/nicolasprochazka/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/signal/signal.go:71 +0xfd
github.com/rtctunnel/rtctunnel/peer.recvSignal({{0x6, 0xc4, 0xbd, 0xdb, 0xcd, 0x57, 0x6e, 0x62, 0x5, 0x2c, ...}, ...}, ...)
	/home/nicolasprochazka/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/peer/conn.go:250 +0x85
github.com/rtctunnel/rtctunnel/peer.Open({{0x6, 0xc4, 0xbd, 0xdb, 0xcd, 0x57, 0x6e, 0x62, 0x5, 0x2c, ...}, ...}, ...)
	/home/nicolasprochazka/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/peer/conn.go:197 +0xa9c
main.init.4.func1(0xc0000a3680, {0x930300, 0x2, 0x2})
	/home/nicolasprochazka/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/cmd/rtctunnel/cmd_run.go:61 +0x5c5
github.com/spf13/cobra.(*Command).execute(0xc0000a3680, {0xc000072380, 0x2, 0x2})
	/home/nicolasprochazka/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xcfde40)
	/home/nicolasprochazka/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/nicolasprochazka/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/nicolasprochazka/go/pkg/mod/github.com/rtctunnel/rtctunnel@v0.6.0/cmd/rtctunnel/main.go:8 +0x25


with config as and 2 peer ( with local/remte peer inverse)
cat /home/nicolasprochazka/.config/rtctunnel/rtctunnel.yaml 
keypair:
  public: TRSqcgGdNCD4Ew3Ueiz8BHm2E65rpTVnn55ogC4xUck
  private: F6A5MDuqty3RMu86K6v83LsAtnDMXdxbhFeK5uAeRHdZ
routes:
- localport: 2222
  localpeer: TRSqcgGdNCD4Ew3Ueiz8BHm2E65rpTVnn55ogC4xUck
  remotepeer: CA1LKWSDV8s3Dm4vos2dsNAFQiHX42umubBiEjbXdR73
  remoteport: 2222
