### ISSUE TITLE
Operator

### ISSUE THREAD

**Issue by gedw99** [rtctunnel/rtctunnel#3]
Can you explain in the readme how to use the code with an operator ?

**Comment by calebdoxsey** [comment]
Do you mean with a custom operator rather than the currently hardcoded:

```go
NewOperatorChannel("https://operator.rtctunnel.com")
```

I'll update the config file so that it supports changing this, and update the readme to explain how change it.

**Comment by gedw99** [comment]
super - thanks.

**Comment by calebdoxsey** [comment]
@gedw99 I updated the code to allow customization of the signal channel. I also updated the readme with an explanation. Feel free to re-open this issue if you had something else in mind. (or if I broke something unintentionally :)).

**Comment by gedw99** [comment]
nice - thanks @calebdoxsey 
will pull and try now...
