### ISSUE TITLE
FATAL[0041] failed to open peer connection error=failed to send webrtc offer: Post https://operator.rtctunnel.com/pub: net/http: request canceled 

### ISSUE THREAD

**Issue by abbabb123** [rtctunnel/rtctunnel#8]
FATAL[0041] failed to open peer connection error=failed to send webrtc offer: Post https://operator.rtctunnel.com/pub: net/http: request canceled

**Comment by calebdoxsey** [comment]
@jans1086 are you still seeing this error? The operator appears to be up to me.

It's possible it was down for a little while. I've added an uptime monitor to keep an eye on it.

I'm considering other operator possibilities but haven't found one that's both free and that requires no initial setup.

**Comment by calebdoxsey** [comment]
Switch to fly.io from heroku. At least until they cancel their free plan :).
